### ISSUE TITLE
Immersive invisible broken wire

### ISSUE THREAD

**Issue by Tsuraname** [Divine-Journey-2/Divine-Journey-2#1155] opened 2024-06-03 13:44 UTC
### Modpack version

2.21.0

### Description

I try to find ores with the core sample miner, and sometimes when i destroy the connector the wire drops, but their is still a connection that hurts you when you run into the blockrange of the wire. It happend on a singleplayer world and a hosted server (Video can be sent per message in dc)

### Steps to reproduce

core sample in a chunk, connect it with a connector and let a relay be on a post (does not matter how it is placed on it)

### Expected behavior

should disconnect and drop the wire

### Your Divine Journey 2 Discord Username

NC_steve#9632

**Comment by WaitingIdly** [comment] 2024-06-03 13:52
can you confirm if this is a duplicate of https://github.com/Divine-Journey-2/Divine-Journey-2/issues/755

**Comment by Tsuraname** [comment] 2024-06-03 14:20
yes, i did not see it at first, sorry

**Comment by WaitingIdly** [comment] 2024-06-03 14:36
totally understandable. sadly, we cannot really resolve this issue at the current time.

**Closed by WaitingIdly** 2024-06-03 14:36 UTC
Labels: Bug, Duplicate
