### ISSUE TITLE
Crash because of dark iron recipes

### ISSUE THREAD

**Issue by Raider180** [Divine-Journey-2/Divine-Journey-2#777] opened 2022-11-08 12:23 UTC
### Modpack version

2.17.1

### Java version

1.8.0_51 ( curseforge )

### RAM Allocated

I use 10GB for the client and I have 32 GB

### Description

Since installing the latest version, my game crash when loading because of a recipe of ender IO ( the dark iron dust used in the dark steel upgrade ) modified by contenttweaker. I tried going back to older version but the same crash happen ( for the exact same reason )

### When did the crash happen?

It happen when the pack is loading , at the initializing mod phase 2 ( part 5/7 )

### Steps to reproduce

Open the game , wait for loading and it will crash

### Minecraft crash report

I don't seem to any crashreport and when i click on the "open latest.log" , nothing happen.

### Additional context

![Screenshot](https://user-images.githubusercontent.com/117734163/200562381-27e26e07-e647-4f15-aaee-818bdb79c429.png)

**Comment by WaitingIdly** [comment] 2022-11-08 14:06
duplicate of #776

**Closed by WaitingIdly** 2022-11-08 14:06 UTC
Labels: Crash
