### ISSUE TITLE
Add Hecate craft to auto infusion Matrix

### ISSUE THREAD

**Issue by MrReps** [Divine-Journey-2/Divine-Journey-2#867] opened 2022-12-21 15:47 UTC
### Describe the feature

Add Hecate's Visage to the infusion multi block

### Reasons why this should be added

The standard infusion have been replaced and it's boring to place it again for one craft :(

**Comment by King65868** [comment] 2022-12-21 17:17
Duplicate of #481

**Closed** 2022-12-21 17:29 UTC
Labels: Duplicate, Feature Request
