### ISSUE TITLE
Can't craft Magical Wood using certain Bookshelves.

### ISSUE THREAD

**Issue by ALazyScientist** [Divine-Journey-2/Divine-Journey-2#1068] opened 2023-11-06 16:29 UTC
### Modpack version

2.20.0

### Description

You're unable to use Bookshelves from natura and quark while crafting magical wood. I need to know if this is only happening to me.

### Steps to reproduce

1. Set up a powered enchanter from Extra Utilities 2 with vanilla bookshelves surrounding it. 
2. Input a bookshelf from either quark or natura and some lapis.
3. Get disappointed when nothing happens.

4. You could also check the recipe by right clicking on a bookshelf from quark or natura using JEI.
5. If it doesn't work then it should look like it's crafting air.

### Expected behavior

You should be able to use bookshelves from any mod when crafting magical wood.

### Your Divine Journey 2 Discord Username

thelazyscientist

**Comment by noel357** [comment] 2023-11-06 16:31
Yeah it's a known bug, tried to use Spruce Bookshelves at first too, then someone said only Oak works.

**Comment by WaitingIdly** [comment] 2023-11-07 02:23
duplicate of #353

**Closed by WaitingIdly** 2023-11-07 02:23 UTC
Labels: Bug
