### ISSUE TITLE
Meteorites not spawning in Atum

### ISSUE THREAD

**Issue by SomeKid17** [Divine-Journey-2/Divine-Journey-2#1158] opened 2024-06-14 23:21 UTC
### Modpack version

2.21.0 (Release)

### Description

AE2 Meteorites are not spawning in the Atum. In Divine Journey 2.20.1 (Previous version) they do spawn. Between that release and the current release ae2 was updated so that might be the cause. I tried updating ae2 extended life from v0.56.4 to v0.56.6 but the meteors still don't spawn.

### Steps to reproduce

Download latest version and go to the Atum and use ae2 compass

### Expected behavior

Should spawn tried to mess with the configs but it didn't fix anything

**Comment by WaitingIdly** [comment] 2024-06-14 23:21
duplicate of #1156 and #1150,

**Closed by WaitingIdly** 2024-06-14 23:21 UTC
Labels: Bug
