### ISSUE TITLE
Enchanter/JEI Recipe bug

### ISSUE THREAD

**Issue by bommerhondjes14** [Divine-Journey-2/Divine-Journey-2#790] opened 2022-11-16 12:01 UTC
### Modpack version

2.7.1

### Description

Items in Ender IO Enchanter give different results than shown in JEI.

### Steps to reproduce

Enchanter:
![image](https://user-images.githubusercontent.com/16944023/202175402-7de32d06-67a6-436c-99b8-8f09041b9463.png)

JEI: 
![image](https://user-images.githubusercontent.com/16944023/202175454-ad133f89-8a56-434b-8225-81e35e94a00e.png)

### Expected behavior

Recipe shown in JEI is same as in the Enchanter

### Your Divine Journey 2 Discord Username

Bommerhond#9411

**Comment by Preta-Crowz** [comment] 2022-11-16 12:56
Duplicate of #779

**Closed** 2022-11-17 00:58 UTC
Labels: Bug
