### ISSUE TITLE
creative item recipe error Reservior（creative）

### ISSUE THREAD

**Issue by jaosnye1012** [Divine-Journey-2/Divine-Journey-2#869] opened 2022-12-25 10:43 UTC
### Modpack version

2.18

### Description

Reservior（creative）recipe error

### Steps to reproduce

![image](https://user-images.githubusercontent.com/59161589/209464669-fba66c36-5cf2-40a2-9c08-2901b0eadea3.png)
![image](https://user-images.githubusercontent.com/59161589/209464836-b0ecee06-2e06-4578-af2b-ed7abbb2cbdd.png)

### Expected behavior

should craft by creative fluid tank

**Comment by King65868** [comment] 2022-12-25 14:16
Still requires a creative fluid tank and duplicate of #716

**Closed by King65868** 2022-12-25 14:16 UTC
Labels: Bug
