### ISSUE TITLE
WARNING -  SLIGHT CH30 SPOILERS

### ISSUE THREAD

**Issue by Craosien** [Divine-Journey-2/Divine-Journey-2#1186] opened 2024-11-11 14:17 UTC
### Modpack version

2.21.1

### Description

The "bug" is caused by thaumcraft giving essentia to ch30 items, and i suggest removing them.

### Steps to reproduce

1. Search @Thaumcraft
2. Click on the uses for the Fabrico essentia (example).
3. Go to the 2nd page
4. You can find (a) ch30 item(s).

### Expected behavior

The essentia from those items should be totally removed since some people can just easily figure out that you can somewhat spoil the contents of chapter 30 upon creating a world.

### Your Divine Journey 2 Discord Username

Crao

**Comment by WaitingIdly** [comment] 2024-11-11 14:18
duplicate of #473

**Closed by WaitingIdly** 2024-11-11 14:18 UTC
Labels: Bug
