### ISSUE TITLE
Suppression reagent recipe bug with buckets

### ISSUE THREAD

**Issue by fluffoo** [Divine-Journey-2/Divine-Journey-2#803] opened 2022-11-20 22:15 UTC
### Modpack version

2.17.1

### Description

The suppression reagent recipe in JEI says to use a bucket of dew of the void and vapor of levity

However when actually crafting suppression reagent any bucket of fluid that is not a vanilla one works for the recipe

### Steps to reproduce

Try to make the suppression reagent in hellfire forge
Use a bucket that is not dew of the void and vapor of levity and is a modded bucket

### Expected behavior

It shouldn't craft suppression reagent unless one dew of the void and one vapor of levity bucket is inputed

### Additional context

https://user-images.githubusercontent.com/66801514/202929190-1ea33345-c65a-45d1-9eea-0d1d273fa255.mp4

### Your Divine Journey 2 Discord Username

Floofy Floofles (She/Her)#9720

**Comment by Preta-Crowz** [comment] 2022-11-21 06:12
it seems nbt were ignored

**Comment by WaitingIdly** [comment] 2024-03-12 18:36
this is a duplicate of #1106, closing this one in favor of that because it has more information about the extent of the issue

**Closed by WaitingIdly** 2024-03-12 18:36 UTC
Labels: Bug
