### ISSUE TITLE
Game crashes on root spell

### ISSUE THREAD

**Issue by Dragonal-Y** [Divine-Journey-2/Divine-Journey-2#714] opened 2022-08-23 10:45 UTC
### Modpack version

2.15.0

### Java version

1.8.0.312

### RAM Allocated

8gs and my pc has 32g

### Description

its caused my roots augment light drivfter

### When did the crash happen?

1h ago

### Steps to reproduce

get into a server
get staff from roots and use the augment spell with light drivfter
game crashes server doesnt

### Minecraft crash report

[crash-2022-08-23_18.18.06-client.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/9401822/crash-2022-08-23_18.18.06-client.txt)

**Comment by WaitingIdly** [comment] 2022-08-23 10:46
duplicate of #698, which has been fixed in dev (via updating roots).

**Closed by WaitingIdly** 2022-08-23 10:46 UTC
Labels: Crash

**Comment by Dragonal-Y** [comment] 2022-08-23 10:51
ah ok thx
