### ISSUE TITLE
The demon will crystal cluster never splits 

### ISSUE THREAD

**Issue by missigno16** [Divine-Journey-2/Divine-Journey-2#670] opened 2022-05-17 01:39 UTC
### Modpack version

2.10.0 - 2.14.2

### Description

So some time ago i did the ritual for the demon will crystal cluster thingy, and the crystal grew all it's clusters, but then it was supossed to split in 4 crystals, and it never did, i swear, i left the game afk for 10 hours, i didn't split, in fact, i believe that more than 48 hours have passed.

![image](https://user-images.githubusercontent.com/65515531/168710013-341f9545-8ae0-4ae5-a59c-5493b9ea4c4f.png)

All the 20 grand tartaric gems are full, and i rebuilt the structures 3 times, i have no idea what's wrong

### Steps to reproduce

Build both the rituals needed, place demon crystalizer and the crucible with the gems, it doesn't work, at least for me

### Expected behavior

The crystals are supposed to split in 4, green, blue, yellow and red

### Additional context

I updated my pack recently, doesn't work still

**Comment by Atricos** [comment] 2022-05-18 17:43
1. Make sure you haven't run out of Life Essence. If you have, make the Well of Suffering Ritual first.
2. Make sure `/gamerule doDaylightCycle` is set to `true`.

**Comment by WaitingIdly** [comment] 2022-06-21 17:32
reading your reproduction steps, i notice that you never activate the ritual. might just be something you missed.
regardless, i cannot replicate this issue, and its been over a month since the last engagement after a pair of possible fixes were suggested, so im closing this issue.
if it still happens and you can confirm specific reproduction steps, please do so here so i may fix this issue.

**Closed by WaitingIdly** 2022-06-21 17:32 UTC
Labels: Bug
