### ISSUE TITLE
Some QoL additions

### ISSUE THREAD

**Issue by Cyber1551** [Divine-Journey-2/Divine-Journey-2#631] opened 2022-02-28 15:21 UTC
### Describe the feature

I was thinking of a couple of quality of life additions. Some of these are already in the discord but I thought I'd add them here.

1. Waystones
2. Earlier access to Void dimensions
3. Xtones, Architechcraft, and carpenters blocks
4. Scannable

### Reasons why this should be added

1. Waystones - Specifically for end portal as it spawns super far away. You would still have to find it normally
2. Earlier access to Void dimensions - Specifically for building preferences
3. Xtones, Architechcraft, and carpenters blocks - Building additions
4. Scannable - Maybe gate it a little. However, this is mainly for erebus, atum, aether, etc where the ore is super rare (especially erebus).

### Describe alternatives you've considered

1. Waystones - Tweak end portal spawn location or allow for endportal frames to be crafted (I know Blood magic has a way to teleport portal frames but it's super late game)
2. Earlier access to Void dimensions - Add "flat plains" mod or similar to allow for nice building areas
3. Scannable - Reduce ore needed from dimensions early game

**Comment by KleinGrrmpf** [comment] 2022-02-28 17:53
For Xtones, ArchitectureCraft and Carpenters' Blocks I am very certain that those will not get added because they add purely visual blocks. They would only increase the load time. But you can of course add them yourself if you are playing on a private server or in Singleplayer.

Regarding Scannable for Erebus I would rather suggest to tune the generation rates of Temple Ore and Bone Ore a little to make them a little more common (if that is possible). Gneiss Ore can easily be found in the desert biome.

**Comment by Cyber1551** [comment] 2022-02-28 19:57
I agree with both of your points. I didn't consider load time so adding the building mods yourself is definitely the best way to go.
Increasing ore gen is another great way to solve this and I'm fine with both.

What are your thoughts on the end portal one? Roots sky-soarer spell makes it super easy to fly. However, it still takes a few minutes and after the 200th time flying for resources or to check on the mob farm/builder (before item transportation becomes available) it gets super tedious

**Comment by WaitingIdly** [comment] 2022-11-05 14:27
a very delayed response to each suggestion brought up:
- Waystones: there are already plenty of ways to obtain teleportation in this pack. adding another is not in the cards. the end is unlocked mid-chapter 10, and teleportation is unlocked mid-chapter 12. you shouldnt be having to make even 20 trips during that time. i don't think this is an issue.
- Earlier access to Void dimensions: i believe the position it is currently obtained in, just a bit prior to interfaces and the explosion of automation, is a good position already, and occurs roughly around where you unlock the copy-paste gadget. i do not think changing its placement is needed, as it happens just prior to the confluence of better ways of building and more reasons to build.
- Xtones, Architechcraft, and carpenters blocks: duplicate of #562
- Scannable: with excavator veins in all of the mentioned dimensions, finding rare ores is just a matter of spending a bit checking the chunks and setting up an excavator. 

i hope these explanations for each of your suggestions is satisfactory. if you disagree with these judgements, i could be convinced otherwise, so if you still think one of these mods is worth it, please do make the case.

**Closed by WaitingIdly** 2022-11-05 14:27 UTC
Labels: Feature Request, Mod Request
