### ISSUE TITLE
Mechanical User and Aerogel crash

### ISSUE THREAD

**Issue by LordDeatHunter** [Divine-Journey-2/Divine-Journey-2#497] opened 2021-10-21 01:08 UTC
**Modpack version:**
2.8.0

**Java version:**
1.8.0_292

**Description:**
Server crashed when adding 16 magical speed upgrades to a Mechanical user in the Aether.
The Mechanical user was connected to a fluid transposer, which was connected to an ender tank with lava (getting a lava bucket, placing it and returning it back in the transposer with a enderio filter), and next to them was an autobreaker.
Restarting the server kept crashing, since the chunk was loaded.
My guess is that the Mechanical user right-clicked a bucket on the aerogel before the autobreaker managed to break it.

**Minecraft crash report:**
https://pastebin.com/3v9fbW0j

**Comment by JohanniklasLp** [comment] 2021-10-21 01:18
duplicate of #395

**Closed as completed** 2021-10-21 03:44 UTC
Labels: Duplicate, Crash
