### ISSUE TITLE
Coralium enchant book from arcane ensorcellator, wrong nbt

### ISSUE THREAD

**Issue by andrelec1** [Divine-Journey-2/Divine-Journey-2#828] opened 2022-11-30 05:35 UTC
### Modpack version

2.17.1

### Description

 coralium enchanted book make in the arcane ensorcellator didn't have right nbt tabg

### Steps to reproduce

Craft coralium book with  the arcane ensorcellator
get this : 

![image](https://user-images.githubusercontent.com/3273204/204715954-731141d1-0d38-4a3b-a28a-3c8cde682924.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/3273204/204715851-5006555a-838a-47d9-b9c8-18c0b5df3d7b.png)
 

### Additional context

wrong nbt

### Your Divine Journey 2 Discord Username

Andrelec1#0001

**Comment by WaitingIdly** [comment] 2022-11-30 05:36
duplicate of #779, fixed in dev

**Closed by WaitingIdly** 2022-11-30 05:36 UTC
Labels: Bug
