### ISSUE TITLE
Enhanced Wireless Charging Antenna add NTB tag on Mekanism tank 

### ISSUE THREAD

**Issue by jaosnye1012** [Divine-Journey-2/Divine-Journey-2#870] opened 2022-12-25 23:05 UTC
### Modpack version

2.18

### Description

Enhanced Wireless Charging Antenna(ender io) will add NBT tag on Mekanism Fluid Tank

### Steps to reproduce

Craft creative Mekanism tank need T4 Mekanism Fluid Tank with one NTB only,Whenever I move Mekanism Fluid Tank to inventory,
The NBT tag will go up to two so I can't craft creative Mekanism tank until turn of Enhanced Wireless Charging Antenna

This is easy to fix but not easy to find

### Expected behavior

add a warning in BQ or recipe accept tank with two NBT tag

**Comment by WaitingIdly** [comment] 2022-12-26 02:54
adding an nbt tag isnt a bug (just a weird interaction). the actual bug is a duplicate of #716. this isnt a separate problem.

**Closed by WaitingIdly** 2022-12-26 02:54 UTC
Labels: Bug
