### ISSUE TITLE
Roots' staff crashes the game

### ISSUE THREAD

**Issue by AyluinReymaer** [Divine-Journey-2/Divine-Journey-2#1124] opened 2024-02-14 02:05 UTC
### Modpack version

2.20.1

### Java version

1.8.0_231

### RAM Allocated

8GBs, my PC has 24GBs

### Description

I am opening the Spell Book for the staff of the Roots mod.

Not even clicking on anything, just opening the spell book and moving the mouse a bit crashes the game.

The spells I have unlocked and added to the staff are Augment and Harvest.

When the game crashes, the game crashed screen specifies that it identified issues with the following mods:

![image](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/51486181/83381a4b-77f4-4507-b02d-bebd520db8dc)

Though what is interesting is that I've replicated this issue twice and for both times, it gave me a different list of mods that had the issue.

The first time, Extra Utilities 2 was not in the list. The second time, it was.

Checking the second crash log, I can also see that extra utilities played a part in the crash

### When did the crash happen?

When opening the Root's spell book and moving the mouse around for a while

### Steps to reproduce

Open the Root's spell book and move the mouse around for a while

### Minecraft crash report

[crash-2024-02-14_01.54.25-server.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/14274425/crash-2024-02-14_01.54.25-server.txt)
[crash-2024-02-14_01.58.27-server.txt](https://github.com/Divine-Journey-2/Divine-Journey-2/files/14274426/crash-2024-02-14_01.58.27-server.txt)

**Comment by Ringedtech203** [comment] 2024-02-14 02:39
Duplicate of #1104 (really not understanding why this issue has not been fixed this yet)

**Comment by AyluinReymaer** [comment] 2024-02-14 11:40
Thank you for the help (:

I did try checking for open issues for potential duplicates and couldn't find any. That one seems to be closed, that would explain why.

Should we keep this issue open while it's not fixed?

It would help others that are facing the same issue and would serve as a reminder as well that it is an active issue that needs solving as well.

**Comment by AyluinReymaer** [comment] 2024-02-14 11:55
By the way, instead of downgrading by 1 version, I bumped **up** the version to the latest 3.1.9.1 instead.

Also works (:

**Comment by noel357** [comment] 2024-02-14 12:16
The issue has been solved by the Roots dev already but there just wasn't a DJ2 update with the new version yet which idk that is. People ask on a daily basis and it has become quite annoying, imo simply make an "emergency" 2.20.2 update only with the new Roots version, people on public servers just can't use any Roots spells I assume.

**Comment by WaitingIdly** [comment] 2024-03-21 16:45
this has been resolved in #1130 via updating Roots

**Closed by WaitingIdly** 2024-03-21 16:45 UTC
Labels: Crash
