### ISSUE TITLE
Hi, my dank got into my ME system and now I can't get it

### ISSUE THREAD

**Issue by SmartErr0r** [Divine-Journey-2/Divine-Journey-2#1148] opened 2024-05-03 09:47 UTC
### Modpack version

2.21.0

### Description

I was putting all my resources into the ME system and accidentally threw the dunk mk2 into it and now it's not possible to take it from there

### Steps to reproduce

1. Open the ME terminal
2. Using the combination space + rmb \ lmb, click on your inventory and all items from the inventory fall into the ME system
3. It is not possible to pick up the Dank mk2.

### Expected behavior

dank has to get out of the system

### Additional context

![image](https://github.com/Divine-Journey-2/Divine-Journey-2/assets/46190598/d9c0fd12-c035-4ad0-9b43-fdb6a17c3f59)

### Your Divine Journey 2 Discord Username

Error#404

**Comment by WaitingIdly** [comment] 2024-05-03 09:49
duplicate of #786

**Closed by WaitingIdly** 2024-05-03 09:49 UTC
Labels: Bug
