### ISSUE TITLE
Chiseled Ender IO Invisible Block unchiselable

### ISSUE THREAD

**Issue by Command-Crafter** [Divine-Journey-2/Divine-Journey-2#280] opened 2021-09-12 15:46 UTC
**Modpack version:**
2.3.0

**Description:**
After using a Chisels and Bits Chisel on an Ender IO Invisible Block, it is not possible to further chisel the block when in Survival Mode. This Issue doesnt appear when in Creative Mode.

**Steps to reproduce:**
1. Get into a Survival World
2. Place an Ender IO Invisible Block
3. Chisel the Block using a Chisels and Bits Chisel
4. Further chiseling is impossible

**Expected behavior:**
Being able to further chisel an already chiseled Invisible Block

**Additional context:**
I tried the exact same setup on a clean instance with only ender io and chisels and bits, and the issue didnt appear.

Adding this to 'config/tool_progression/tool_overwrites.cfg' fixes the issue, so it seems to have something to do with mining level.
```
	S:"chiselsandbits:chisel_diamond"=pickaxe=12
```

**Comment by afanofabba** [comment] 2021-09-16 17:21
In version 2.3.1, the same bug is occurring with multiple block types, not just Ender IO Invisible blocks. I followed the steps to reproduce using blocks from other mods as well as minecraft blocks (not invisible) and was unable to continue to chisel after chisels once with the chisel.

**Comment by Command-Crafter** [comment] 2021-09-17 21:05
Its probably a weird bug that increases the block hardness after chiseling, since increasing the chisel mining level fixes it.

**Comment by Atricos** [comment] 2021-09-18 11:41
I don't want to turn the Diamond Chisel into a powerful Pickaxe, there is a reason some of the later game Pickaxes have a higher mining level.

Can you list more (or all) blocks this is happening to?

**Comment by Command-Crafter** [comment] 2021-09-18 16:57
The Chisel cannot function as a pickaxe, you cant mine blocks with it, you can only relocate them.

**Comment by Ringedtech203** [comment] 2021-10-13 20:54
using a positive pattern for the full block and a bit bag in the crafting window allows you to craft a full block out of bits![2021-10-13_17 46 23](https://user-images.githubusercontent.com/44550133/137210877-e7ef9eb1-8297-4a30-96cd-a092ffce6cbe.png)

**Comment by KleinGrrmpf** [comment] 2021-10-13 22:14
I didn't know you could make blueprints out of full blocks either ^^
But still, I'm sticking to my point that using chisels to mine Ethaxium is not worth it just because of how much you need and how little space there is, even if you have a full inventory of bit bags. And if fullBlockCrafting is disabled, there is nothing to worry about because you can't get the blocks by crafting.

**Comment by Atricos** [comment] 2022-05-03 23:02
Fixed in 2.14.0. Better late than never!

**Closed by Atricos** 2022-05-03 23:02 UTC
Labels: Bug
