### ISSUE TITLE
Meteorite Compass doesn't work in Atum 2

### ISSUE THREAD

**Issue by dviedooo** [Divine-Journey-2/Divine-Journey-2#1156] opened 2024-06-03 21:34 UTC
### Modpack version

2.21.0

### Description

When I enter Atum and go travel, I can not get any tracking of meteorites from the compass, it just spins slowly 

### Steps to reproduce

1.Get into the Atum 2 dimention 
2.Take out the Meteorite Compass
3.Watch it spin while traveling through the dimention
4.Never stumble upon any traction 

### Expected behavior

The compass should have pointed to the meteorites direction

**Comment by WaitingIdly** [comment] 2024-06-03 21:51
duplicate of https://github.com/Divine-Journey-2/Divine-Journey-2/issues/1150 and resolved in dev

**Closed by WaitingIdly** 2024-06-03 21:51 UTC
Labels: Bug
